---
##################
# System
##################
system_update: true
system_update_security_only: false

system_packages_install:
  - wget
  - curl
  - htop
  - p7zip-full
  - p7zip-rar
  - dos2unix
  - network-manager
  - network-manager-openvpn
  - jq
  - jmtpfs
  - dar
  - terminator
  - net-tools
  - gnome-shell-extensions
  - gnome-tweak-tool
  - ubuntu-restricted-extras
  - tlp
  - tlp-rdw
  - virtualbox
  - whois
  - ipcalc
  # -------------------------------------------------
  # Package for system-monitor gnome shell extension
  # -------------------------------------------------
  - gir1.2-gtop-2.0
  - gir1.2-networkmanager-1.0
  - gir1.2-clutter-1.0

system_packages_remove:
  - light-locker
  - nano

system_deb_urls:
  - "https://prerelease.keybase.io/keybase_amd64.deb"

system_clean: true

##################
# Tools
###################

## ZSH install
oh_my_zsh_custom_theme_info: { url: "https://github.com/ptavares/zsh-themes.git", dir_dest_name: zsh-themes }
oh_my_zsh_custom_theme: ptavares

oh_my_zsh_default_plugins:
  - git
  - colored-man-pages
  - ubuntu
  - aws
  - tmux

oh_my_zsh_custom_plugins_info:
  - { url: "https://github.com/junegunn/fzf.git", dir_dest_name : fzf }
  - { url: "https://github.com/Treri/fzf-zsh.git", dir_dest_name: fzf-zsh }
  - { url: "https://github.com/zsh-users/zsh-autosuggestions.git", dir_dest_name: zsh-autosuggestions }
  - { url: "https://github.com/zdharma/fast-syntax-highlighting.git", dir_dest_name: fast-syntax-highlighting }

oh_my_zsh_custom_plugins:
  - fzf-zsh
  - zsh-autosuggestions
  - fast-syntax-highlighting

oh_my_zsh_custom_plugins_command :
  - "$HOME/.oh-my-zsh/custom/plugins/fzf/install --all"
  - "fast-theme safari"

oh_my_zsh_custom_zsh_entries:
  - "# List only directories alias"
  - "alias lsd='ls -l | grep \"^d\"'"
  - "# List by size directories"
  - "alias ducks='du -cksh * | sort -hr | head -n 15'"
  - "# File Shortcuts"
  - "alias D='cd ~/Téléchargements'"
  - "alias p='cd ~/projects'"
  - "alias T='cd ~/tools'"
  - "# Program Shortcuts"
  - "alias gitStoreCredentials='git config credential.helper store'"
  - "alias vi='vim -O'"
  - "# AWS login"
  - "alias logIntoIpponAWS='aws-google-auth -p ippon-admin-aws -d 28800 -I C00lefphs -S 563310275444 -r arn:aws:iam::308846910468:role/role-admin-sre-ops-federated -u ptavares@ippon.fr'"
  - "# Tools Docker alias"
  - "# kubectl completion"
  - "if [ /usr/local/bin/kubectl ]; then source <(kubectl completion zsh); fi"
  - "# List all AWS profiles"
  - "alias listAwsProfiles=\"grep '^[[]profile' <~/.aws/config | awk '{print $2}' | sed 's/]$//'\""


## Shell Extension install
shell_extension_items:
  - {name : "Alternate Tab" , id: 15, shell_version: "" }
  - {name : "System Monitor" , id: 120, shell_version: "" }
  - {name : "Dash to Dock" , id: 307, shell_version: "" }
  - {name : "Workspace Isolate Dash" , id: 887, shell_version: "" }
  - {name : "Workspace Grid" , id: 484, shell_version: "" }
  - {name : "Workspace Indicator" , id: 21, shell_version: "" }

### Visual studio code
# Install last version
visual_studio_code_version: ''

### Docker : no version specified -> install last version
### Install docker-compose to last version to
docker_users:
    - ptavares

### Terraform : no version specified -> install last version
#terraform_install_version: 0.11.8
### Terragrunt : same as terraform
# terragrunt_install_version: v0.16.7
### Kubectl
kubectl_install_version: v1.11.2
