---
terragrunt_install_version: v0.16.7
terragrunt_url: "https://github.com/gruntwork-io/terragrunt/releases/download/{{ terragrunt_install_version }}/terragrunt_linux_amd64"
terragrunt_download_location: /tmp/
terragrunt_downloaded_file_name: terragrunt_linux_amd64
terragrunt_execution_path: /usr/local/bin
terragrunt_execution_file_name: terragrunt
