- src: ptavares.ansible_role_manage_system
- src: ptavares.ansible_role_oh_my_zsh
- src: ptavares.ansible_role_docker
- src: ptavares.ansible_role_terraform
- src: ptavares.ansible_role_terragrunt
- src: gantsign.visual-studio-code