---
- name: "Initialize laptop from scratch"
  hosts: localhost
  gather_facts: true
  connection: local

  # Ask for sudo password
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes

  roles:
    - { name: ptavares.ansible_role_manage_system, tags: [system, init] }
    - { name: shell-extension, tags: [tools, system, shell-extension] }
    - { name: ptavares.ansible_role_oh_my_zsh, tags: [tools, bash, zsh] }
    - { name: tmux, tags: [tools, bash, tmux] }
    - { name: gantsign.visual-studio-code, tags: [tools, editor, vsc] }
    - { name: vim, tags: [tools, editor, vim] }
    - { name: ptavares.ansible_role_terraform, tags: [tools, terraform] }
    - { name: ptavares.ansible_role_terragrunt, tags: [tools, terragrunt] }
    - { name: ptavares.ansible_role_docker, tags: [tools, docker] }
    - { name: kubectl, tags: [tools, kubectl] }