---
- name: "Update laptop"
  hosts: localhost
  gather_facts: true
  connection: local

  # Ask for sudo password
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes

  tasks:
    - include_role:
         name: ptavares.ansible_role_manage_system
      tags:
        - system
